// Catalogo de ejercicios por grupo muscular.
// Cada ejercicio incluye info util para mostrar en la tarjeta expandida:
// equipo necesario, musculo principal, como ejecutarlo y un consejo clave.

export const muscleGroups = [
  {
    slug: "pecho",
    name: "Pecho",
    accent: "#b56cff",
    exercises: [
      { name: "Press de banca", equipment: "Barra y banco plano", primary: "Pectoral mayor", description: "Acostado en el banco, baja la barra de forma controlada hasta rozar el pecho y empuja hacia arriba extendiendo los codos sin bloquearlos.", tip: "Manten los omoplatos retraidos y los pies firmes en el piso durante todo el movimiento." },
      { name: "Press inclinado con mancuernas", equipment: "Mancuernas y banco inclinado", primary: "Pectoral superior", description: "En un banco a 30-45 grados, empuja las mancuernas hacia arriba juntandolas cerca de la parte alta del pecho.", tip: "Evita que el banco supere los 45 grados para no desviar el trabajo hacia el hombro." },
      { name: "Aperturas con mancuernas", equipment: "Mancuernas y banco plano", primary: "Pectoral (fibras externas)", description: "Con los brazos ligeramente flexionados, abre los brazos en arco hasta sentir el estiramiento del pecho y regresa juntando las mancuernas arriba.", tip: "El movimiento es de bisagra en el hombro, no en el codo." },
      { name: "Fondos en paralelas", equipment: "Barras paralelas", primary: "Pectoral inferior y triceps", description: "Inclina el torso hacia adelante y baja el cuerpo doblando los codos hasta 90 grados, luego empuja hacia arriba.", tip: "Inclinarte mas hacia adelante enfatiza mas el pecho que el triceps." },
      { name: "Press en maquina", equipment: "Maquina de press de pecho", primary: "Pectoral mayor", description: "Sentado con la espalda apoyada, empuja las manijas hacia adelante hasta extender los brazos sin bloquear los codos.", tip: "Ideal para aprender la tecnica del press sin preocuparte por el equilibrio de la barra." },
      { name: "Press declinado", equipment: "Barra o mancuernas y banco declinado", primary: "Pectoral inferior", description: "En un banco inclinado hacia abajo, baja el peso hasta la parte baja del pecho y empuja en linea recta hacia arriba.", tip: "Asegura bien los pies en los soportes del banco antes de empezar." },
      { name: "Cruces en polea (cable crossover)", equipment: "Maquina de poleas", primary: "Pectoral (fibras internas)", description: "De pie en el centro de la polea, junta las manos frente al pecho en un movimiento de arco controlado.", tip: "Da un pequeno paso adelante para mantener tension constante en el cable." },
      { name: "Flexiones de pecho (push-ups)", equipment: "Peso corporal", primary: "Pectoral mayor y core", description: "Con las manos un poco mas anchas que los hombros, baja el pecho hasta casi tocar el piso y empuja hacia arriba manteniendo el cuerpo recto.", tip: "Aprieta el abdomen para evitar que la cadera se hunda." },
      { name: "Pullover con mancuerna", equipment: "Mancuerna y banco plano", primary: "Pectoral y dorsal", description: "Acostado transversal al banco, baja la mancuerna detras de la cabeza en arco y regresa por el mismo camino.", tip: "Manten una ligera flexion de codos fija durante todo el recorrido." },
      { name: "Press con banda elastica", equipment: "Banda de resistencia", primary: "Pectoral mayor", description: "Con la banda anclada detras de ti, empuja hacia adelante extendiendo los brazos a la altura del pecho.", tip: "Muy util para calentar antes de levantar peso libre." },
    ],
  },
  {
    slug: "espalda",
    name: "Espalda",
    accent: "#5ba8ff",
    exercises: [
      { name: "Dominadas", equipment: "Barra de dominadas", primary: "Dorsal ancho", description: "Cuelga de la barra con agarre prono y sube el cuerpo hasta que la barbilla pase la barra, controlando la bajada.", tip: "Si no puedes hacer una completa, usa una banda de asistencia o la maquina asistida." },
      { name: "Jalon al pecho", equipment: "Maquina de polea alta", primary: "Dorsal ancho", description: "Sentado, tira de la barra hacia la parte alta del pecho llevando los codos hacia abajo y atras.", tip: "Evita balancear el torso hacia atras para usar impulso." },
      { name: "Remo con barra", equipment: "Barra libre", primary: "Dorsal y trapecio medio", description: "Con el torso inclinado hacia adelante, tira de la barra hacia el abdomen apretando los omoplatos.", tip: "Manten la espalda recta y la mirada al frente para proteger la zona lumbar." },
      { name: "Remo con mancuerna a un brazo", equipment: "Mancuerna y banco", primary: "Dorsal ancho", description: "Apoya una rodilla y una mano en el banco, y tira de la mancuerna hacia la cadera manteniendo el codo cerca del cuerpo.", tip: "Gira ligeramente el torso al final para exprimir la contraccion." },
      { name: "Jalon con agarre cerrado", equipment: "Maquina de polea alta", primary: "Dorsal (fibras bajas)", description: "Con un agarre estrecho en V, tira de la barra hacia el pecho llevando los codos pegados al cuerpo.", tip: "Controla la fase excentrica (subida) para no perder tension." },
      { name: "Remo en maquina sentado", equipment: "Maquina de remo (cable horizontal)", primary: "Dorsal y trapecio medio", description: "Sentado con las rodillas semiflexionadas, tira de las manijas hacia el abdomen manteniendo el pecho erguido.", tip: "No dejes que la espalda baja se redondee al estirar los brazos." },
      { name: "Peso muerto convencional", equipment: "Barra libre", primary: "Espalda baja, gluteos e isquiotibiales", description: "Con la barra cerca de las espinillas, levanta el peso extendiendo cadera y rodillas a la vez, manteniendo la espalda neutra.", tip: "Aprende la tecnica con poco peso antes de progresar; es clave para evitar lesiones." },
      { name: "Hiperextensiones", equipment: "Banco romano", primary: "Espalda baja (erectores espinales)", description: "Con la cadera apoyada en el banco, baja el torso controladamente y sube hasta alinear el cuerpo.", tip: "No hiperextiendas de mas al subir, solo hasta la linea recta." },
      { name: "Dominadas asistidas", equipment: "Maquina asistida o banda", primary: "Dorsal ancho", description: "Igual que la dominada tradicional, pero con soporte que reduce el peso a levantar.", tip: "Buena opcion para ganar fuerza progresivamente hacia la dominada libre." },
      { name: "Face pull", equipment: "Polea con cuerda", primary: "Trapecio y deltoide posterior", description: "Tira de la cuerda hacia la cara separando las manos al final del recorrido.", tip: "Excelente para mejorar la postura y la salud del hombro." },
    ],
  },
  {
    slug: "hombros",
    name: "Hombros",
    accent: "#ffb84d",
    exercises: [
      { name: "Press militar con barra", equipment: "Barra libre", primary: "Deltoide anterior", description: "De pie o sentado, empuja la barra desde los hombros hacia arriba hasta extender los brazos por completo.", tip: "Aprieta los gluteos y el abdomen para no arquear la espalda baja." },
      { name: "Elevaciones laterales", equipment: "Mancuernas", primary: "Deltoide medio (lateral)", description: "Con los brazos ligeramente flexionados, eleva las mancuernas hacia los lados hasta la altura de los hombros.", tip: "Sube liderando con los codos, no con las munecas." },
      { name: "Press Arnold", equipment: "Mancuernas", primary: "Deltoide (los tres haces)", description: "Empieza con las palmas hacia ti y rota las munecas hacia afuera mientras empujas las mancuernas hacia arriba.", tip: "Controla bien la rotacion, es lo que distingue este ejercicio del press normal." },
      { name: "Pajaro con mancuernas (elevacion posterior)", equipment: "Mancuernas", primary: "Deltoide posterior", description: "Inclinado hacia adelante, eleva las mancuernas hacia los lados apretando los omoplatos.", tip: "Usa un peso liviano; es un musculo pequeno y facil de compensar con impulso." },
      { name: "Press de hombros en maquina", equipment: "Maquina de press de hombros", primary: "Deltoide anterior", description: "Sentado con la espalda apoyada, empuja las manijas hacia arriba sin bloquear los codos al final.", tip: "Buena opcion para aislar el hombro sin estabilizar peso libre." },
      { name: "Elevaciones frontales", equipment: "Mancuernas o disco", primary: "Deltoide anterior", description: "Eleva el peso al frente hasta la altura de los hombros con los brazos casi extendidos.", tip: "No balancees el torso hacia atras para tomar impulso." },
      { name: "Remo al menton (upright row)", equipment: "Barra o mancuernas", primary: "Deltoide medio y trapecio", description: "Tira del peso verticalmente hacia el menton manteniendo los codos por encima de las munecas.", tip: "Si sientes molestia en el hombro, usa un agarre mas ancho o baja el rango de movimiento." },
      { name: "Encogimientos (shrugs)", equipment: "Mancuernas o barra", primary: "Trapecio superior", description: "Con los brazos extendidos a los lados, eleva los hombros hacia las orejas y baja controladamente.", tip: "Evita rotar los hombros; el movimiento es solo hacia arriba y abajo." },
      { name: "Press tras nuca en polea", equipment: "Polea o maquina", primary: "Deltoide anterior y medio", description: "Empuja el peso desde la parte alta de la espalda hacia arriba, con control en todo el recorrido.", tip: "Solo recomendable si tienes buena movilidad de hombro." },
      { name: "Face pull con polea", equipment: "Polea con cuerda", primary: "Deltoide posterior y rotadores", description: "Tira de la cuerda hacia la cara separando las manos al final del recorrido, con los codos altos.", tip: "Ideal como ejercicio de salud articular para el hombro." },
    ],
  },
  {
    slug: "brazos",
    name: "Brazos",
    accent: "#ff7f7f",
    exercises: [
      { name: "Curl alterno con mancuernas", equipment: "Mancuernas", primary: "Biceps braquial", description: "Alternando brazos, flexiona el codo llevando la mancuerna hacia el hombro sin mover el torso.", tip: "Manten el codo fijo pegado al cuerpo durante todo el recorrido." },
      { name: "Extension de triceps en polea", equipment: "Polea alta con barra o cuerda", primary: "Triceps", description: "Con los codos fijos a los lados del torso, extiende los brazos hacia abajo hasta bloquear.", tip: "No dejes que los codos se separen del cuerpo hacia afuera." },
      { name: "Curl martillo", equipment: "Mancuernas", primary: "Biceps y braquial", description: "Con agarre neutro (palmas enfrentadas), flexiona el codo llevando la mancuerna hacia el hombro.", tip: "Este agarre tambien fortalece el antebrazo." },
      { name: "Fondos en banco (dips de triceps)", equipment: "Banco", primary: "Triceps", description: "Con las manos apoyadas en el borde del banco y piernas extendidas, baja el cuerpo doblando los codos y empuja de vuelta.", tip: "Manten los codos apuntando hacia atras, no hacia los lados." },
      { name: "Curl con barra Z", equipment: "Barra Z (EZ)", primary: "Biceps braquial", description: "Con agarre en la barra Z, flexiona ambos codos llevando la barra hacia el pecho.", tip: "La barra Z reduce la tension en las munecas comparado con la barra recta." },
      { name: "Press frances (extension con barra sobre la cabeza)", equipment: "Barra Z o mancuerna", primary: "Triceps (cabeza larga)", description: "Acostado o de pie, baja el peso detras de la cabeza flexionando solo el codo y extiende de vuelta.", tip: "Usa poco peso al inicio; es un ejercicio exigente para el codo." },
      { name: "Curl concentrado", equipment: "Mancuerna y banco", primary: "Biceps braquial", description: "Sentado, apoya el codo en el interior del muslo y flexiona la mancuerna hacia el hombro.", tip: "Excelente para enfocarte en la contraccion maxima del biceps." },
      { name: "Patada de triceps (kickback)", equipment: "Mancuerna", primary: "Triceps", description: "Inclinado hacia adelante con el codo fijo a la altura de la cadera, extiende el antebrazo hacia atras.", tip: "Manten el brazo superior quieto; solo se mueve el antebrazo." },
      { name: "Curl en polea baja", equipment: "Polea baja con barra", primary: "Biceps braquial", description: "De pie frente a la polea, flexiona los codos llevando la barra hacia el pecho.", tip: "La polea mantiene tension constante en todo el rango de movimiento." },
      { name: "Fondos entre bancos", equipment: "Dos bancos o sillas", primary: "Triceps", description: "Con las manos en un banco y talones en otro, baja el cuerpo doblando los codos y empuja hacia arriba.", tip: "Agrega peso sobre las piernas cuando el ejercicio se sienta facil." },
    ],
  },
  {
    slug: "biceps",
    name: "Biceps",
    accent: "#ff9ecb",
    exercises: [
      { name: "Curl con barra", equipment: "Barra recta o Z", primary: "Biceps braquial", description: "De pie, flexiona ambos codos llevando la barra hacia el pecho sin balancear el torso.", tip: "Evita usar impulso de la cadera; deja que trabaje solo el biceps." },
      { name: "Curl inclinado con mancuernas", equipment: "Mancuernas y banco inclinado", primary: "Biceps (cabeza larga)", description: "Recostado en un banco a 45-60 grados, flexiona los codos con los brazos colgando a los lados.", tip: "La inclinacion del banco aumenta el estiramiento del biceps al inicio del movimiento." },
      { name: "Curl concentrado", equipment: "Mancuerna y banco", primary: "Biceps braquial", description: "Sentado, apoya el codo en el muslo y flexiona la mancuerna hasta el hombro.", tip: "Aprieta 1-2 segundos en la contraccion maxima." },
      { name: "Curl martillo", equipment: "Mancuernas", primary: "Biceps y braquial", description: "Con agarre neutro, flexiona el codo llevando la mancuerna hacia el hombro sin girar la muneca.", tip: "Ayuda a dar grosor al brazo trabajando el musculo braquial." },
      { name: "Curl en polea baja", equipment: "Polea baja", primary: "Biceps braquial", description: "De pie, flexiona los codos llevando la barra o cuerda hacia el pecho con tension constante.", tip: "Ideal para el final de la rutina por su tension continua." },
      { name: "Curl 21s", equipment: "Barra o mancuernas", primary: "Biceps braquial (todo el rango)", description: "Haz 7 repeticiones de la mitad inferior, 7 de la mitad superior y 7 completas, sin soltar el peso.", tip: "Tecnica avanzada para generar mas fatiga metabolica al final de la rutina." },
      { name: "Curl arana (spider curl)", equipment: "Mancuernas o barra Z y banco inclinado", primary: "Biceps (pico)", description: "Recostado boca abajo en un banco inclinado, flexiona los codos dejando los brazos colgar libremente.", tip: "Elimina el impulso del cuerpo por completo, ideal para aislar el biceps." },
      { name: "Curl con banda elastica", equipment: "Banda de resistencia", primary: "Biceps braquial", description: "Con un pie sobre la banda, flexiona el codo llevando la mano hacia el hombro.", tip: "Buena alternativa cuando no tienes mancuernas disponibles." },
      { name: "Curl de arrastre (drag curl)", equipment: "Barra", primary: "Biceps braquial", description: "Sube la barra pegada al cuerpo, arrastrandola verticalmente en vez de en arco.", tip: "Reduce la participacion del hombro y enfatiza mas el biceps." },
      { name: "Curl alterno sentado", equipment: "Mancuernas y banco", primary: "Biceps braquial", description: "Sentado para evitar impulso, flexiona los codos alternando brazos.", tip: "Estar sentado te obliga a controlar mejor la tecnica." },
    ],
  },
  {
    slug: "triceps",
    name: "Triceps",
    accent: "#7fd6c2",
    exercises: [
      { name: "Press frances", equipment: "Barra Z o mancuerna", primary: "Triceps (cabeza larga)", description: "Acostado, baja el peso hacia la frente flexionando solo el codo y extiende de vuelta.", tip: "Manten los codos apuntando al techo durante todo el ejercicio." },
      { name: "Extension en polea con cuerda", equipment: "Polea alta y cuerda", primary: "Triceps", description: "Con los codos fijos junto al torso, extiende los brazos hacia abajo separando la cuerda al final.", tip: "Separar la cuerda al final aumenta la contraccion del triceps." },
      { name: "Fondos en banco", equipment: "Banco", primary: "Triceps", description: "Con las manos en el borde del banco, baja el cuerpo doblando los codos y empuja de regreso.", tip: "Extiende las piernas para aumentar la dificultad." },
      { name: "Extension sobre la cabeza con mancuerna", equipment: "Mancuerna", primary: "Triceps (cabeza larga)", description: "Con ambas manos sosteniendo una mancuerna sobre la cabeza, baja detras del cuello flexionando el codo.", tip: "Manten los codos cerca de las orejas, sin abrirlos hacia los lados." },
      { name: "Patada de triceps (kickback)", equipment: "Mancuerna", primary: "Triceps", description: "Inclinado hacia adelante con el codo fijo, extiende el antebrazo hacia atras hasta bloquear.", tip: "Usa un peso ligero para mantener buena tecnica." },
      { name: "Press cerrado en banca", equipment: "Barra y banco plano", primary: "Triceps y pectoral", description: "Con agarre estrecho (ancho de hombros), baja la barra al pecho y empuja hacia arriba.", tip: "Manten los codos cerca del torso durante el descenso." },
      { name: "Extension en polea con barra", equipment: "Polea alta y barra recta", primary: "Triceps", description: "Con los codos fijos, empuja la barra hacia abajo hasta extender por completo los brazos.", tip: "No dejes que los codos se muevan hacia adelante." },
      { name: "Fondos en paralelas (enfoque triceps)", equipment: "Barras paralelas", primary: "Triceps", description: "Manteniendo el torso mas vertical que en el enfoque de pecho, baja y sube doblando los codos.", tip: "Un torso mas erguido enfatiza mas el triceps que el pecho." },
      { name: "Extension a un brazo en polea", equipment: "Polea alta", primary: "Triceps", description: "Con un brazo a la vez, extiende el antebrazo hacia abajo manteniendo el codo fijo junto al cuerpo.", tip: "Permite corregir desequilibrios de fuerza entre ambos brazos." },
      { name: "Flexiones con manos cerradas (diamond push-ups)", equipment: "Peso corporal", primary: "Triceps", description: "Con las manos juntas formando un diamante bajo el pecho, baja y empuja el cuerpo hacia arriba.", tip: "Manten el core apretado para no arquear la espalda baja." },
    ],
  },
  {
    slug: "piernas",
    name: "Piernas",
    accent: "#6fcf97",
    exercises: [
      { name: "Sentadilla libre", equipment: "Barra libre", primary: "Cuadriceps, gluteos e isquiotibiales", description: "Con la barra sobre los trapecios, baja flexionando cadera y rodillas hasta que los muslos queden paralelos al piso, luego sube.", tip: "Manten el pecho arriba y las rodillas alineadas con los pies." },
      { name: "Prensa de piernas", equipment: "Maquina de prensa", primary: "Cuadriceps y gluteos", description: "Empuja la plataforma extendiendo las piernas sin bloquear por completo las rodillas.", tip: "No dejes que la espalda baja se despegue del respaldo." },
      { name: "Peso muerto rumano", equipment: "Barra o mancuernas", primary: "Isquiotibiales y gluteos", description: "Con las rodillas ligeramente flexionadas, baja el peso deslizandolo cerca de las piernas manteniendo la espalda recta.", tip: "El movimiento nace de la cadera, no de la espalda baja." },
      { name: "Zancadas caminando", equipment: "Mancuernas (opcional)", primary: "Cuadriceps y gluteos", description: "Da un paso largo hacia adelante y baja la rodilla trasera casi hasta el piso, luego alterna la pierna.", tip: "Manten el torso erguido durante todo el movimiento." },
      { name: "Extension de cuadriceps", equipment: "Maquina de extension", primary: "Cuadriceps", description: "Sentado, extiende las piernas hasta casi bloquear las rodillas y baja controladamente.", tip: "Evita usar impulso; controla especialmente la bajada." },
      { name: "Curl femoral (leg curl)", equipment: "Maquina de curl femoral", primary: "Isquiotibiales", description: "Acostado o sentado, flexiona las rodillas llevando los talones hacia los gluteos.", tip: "No arquees la cadera para compensar; manten el torso fijo." },
      { name: "Sentadilla bulgara", equipment: "Mancuernas y banco", primary: "Cuadriceps y gluteos", description: "Con el pie trasero apoyado en un banco, baja flexionando la rodilla delantera hasta 90 grados.", tip: "Excelente para corregir desequilibrios entre ambas piernas." },
      { name: "Zancada estatica (split squat)", equipment: "Mancuernas (opcional)", primary: "Cuadriceps y gluteos", description: "En posicion de zancada fija, baja y sube sin mover los pies del sitio.", tip: "Buena progresion antes de pasar a zancadas caminando." },
      { name: "Sentadilla goblet", equipment: "Mancuerna o kettlebell", primary: "Cuadriceps y gluteos", description: "Sostiene el peso frente al pecho y baja en sentadilla manteniendo el torso erguido.", tip: "Ideal para aprender la tecnica correcta de la sentadilla." },
      { name: "Hip thrust", equipment: "Barra y banco", primary: "Gluteos e isquiotibiales", description: "Con la espalda apoyada en el banco y la barra sobre la cadera, empuja la cadera hacia arriba hasta extender por completo.", tip: "Aprieta fuerte los gluteos en la parte alta del movimiento." },
    ],
  },
  {
    slug: "muslos",
    name: "Muslos",
    accent: "#8fd14f",
    exercises: [
      { name: "Sentadilla goblet", equipment: "Mancuerna o kettlebell", primary: "Cuadriceps interno", description: "Sostiene el peso frente al pecho, con los pies un poco mas abiertos que el ancho de hombros, y baja en sentadilla.", tip: "Empuja las rodillas hacia afuera al bajar para activar el muslo interno." },
      { name: "Zancadas", equipment: "Mancuernas (opcional)", primary: "Cuadriceps y aductores", description: "Da un paso al frente y baja la rodilla trasera casi hasta el piso, alternando piernas.", tip: "Da pasos de longitud consistente para trabajar ambas piernas igual." },
      { name: "Extension de cuadriceps", equipment: "Maquina de extension", primary: "Cuadriceps", description: "Sentado, extiende las piernas y baja controladamente sin soltar el peso de golpe.", tip: "Haz una pausa de 1 segundo arriba para mayor activacion." },
      { name: "Aductores en maquina", equipment: "Maquina de aductores", primary: "Muslo interno (aductores)", description: "Sentado, junta las piernas presionando contra las almohadillas de la maquina.", tip: "Controla tambien el regreso, no dejes que las piernas se abran de golpe." },
      { name: "Abductores en maquina", equipment: "Maquina de abductores", primary: "Muslo externo (gluteo medio)", description: "Sentado, separa las piernas presionando contra las almohadillas hacia afuera.", tip: "Manten la espalda apoyada en el respaldo durante el ejercicio." },
      { name: "Sentadilla sumo", equipment: "Mancuerna o barra", primary: "Cuadriceps y aductores", description: "Con los pies bien abiertos y las puntas hacia afuera, baja en sentadilla manteniendo el torso erguido.", tip: "La postura amplia enfatiza mas el muslo interno que la sentadilla tradicional." },
      { name: "Sentadilla bulgara", equipment: "Mancuernas y banco", primary: "Cuadriceps", description: "Con el pie trasero elevado en un banco, baja flexionando la rodilla delantera.", tip: "Reduce la carga si sientes molestia en la rodilla delantera." },
      { name: "Step-up (subida al cajon)", equipment: "Banco o cajon y mancuernas", primary: "Cuadriceps y gluteos", description: "Sube todo el cuerpo al cajon apoyando un pie, extendiendo la pierna por completo arriba.", tip: "Evita impulsarte con la pierna de atras; que trabaje la de arriba." },
      { name: "Prensa con pies juntos", equipment: "Maquina de prensa", primary: "Cuadriceps (enfoque externo)", description: "Con los pies juntos en la plataforma, empuja extendiendo las piernas sin bloquear del todo.", tip: "Esta variante enfatiza mas la parte externa del muslo." },
      { name: "Sentadilla isometrica en pared (wall sit)", equipment: "Peso corporal", primary: "Cuadriceps (resistencia)", description: "Apoya la espalda en una pared y manten la posicion de sentadilla con las rodillas a 90 grados.", tip: "Aumenta el tiempo poco a poco; es un gran ejercicio de resistencia muscular." },
    ],
  },
  {
    slug: "gluteos",
    name: "Gluteos",
    accent: "#ff8fa3",
    exercises: [
      { name: "Hip thrust", equipment: "Barra y banco", primary: "Gluteo mayor", description: "Con la espalda apoyada en el banco y la barra sobre la cadera, empuja hacia arriba hasta extender por completo la cadera.", tip: "Aprieta con fuerza los gluteos en la parte mas alta del movimiento." },
      { name: "Puente de gluteos", equipment: "Peso corporal o disco", primary: "Gluteo mayor", description: "Acostado boca arriba con las rodillas flexionadas, eleva la cadera apretando los gluteos.", tip: "Buena progresion antes de pasar al hip thrust con peso." },
      { name: "Patada de gluteo en polea", equipment: "Polea baja con tobillera", primary: "Gluteo mayor", description: "De pie, empuja una pierna hacia atras y arriba manteniendo la rodilla ligeramente flexionada.", tip: "No arquees la espalda baja para ganar mas rango de movimiento." },
      { name: "Sentadilla sumo", equipment: "Mancuerna o barra", primary: "Gluteos y aductores", description: "Con los pies bien abiertos, baja en sentadilla manteniendo el torso erguido y las rodillas alineadas con los pies.", tip: "La postura amplia activa mas el gluteo que la sentadilla tradicional." },
      { name: "Peso muerto rumano", equipment: "Barra o mancuernas", primary: "Gluteos e isquiotibiales", description: "Con las rodillas ligeramente flexionadas, baja el peso cerca de las piernas manteniendo la espalda recta.", tip: "Siente el estiramiento en los isquios antes de subir de vuelta." },
      { name: "Zancadas con paso atras (reverse lunge)", equipment: "Mancuernas (opcional)", primary: "Gluteo mayor", description: "Da un paso hacia atras y baja la rodilla trasera casi hasta el piso, luego regresa a la posicion inicial.", tip: "Empuja con el talon de la pierna delantera para activar mas el gluteo." },
      { name: "Abduccion de cadera en maquina", equipment: "Maquina de abductores", primary: "Gluteo medio", description: "Sentado, separa las piernas presionando contra las almohadillas hacia afuera.", tip: "Este ejercicio ayuda a estabilizar la cadera y prevenir lesiones." },
      { name: "Patada de burro (donkey kick)", equipment: "Peso corporal o tobillera con peso", primary: "Gluteo mayor", description: "En posicion de cuadrupedia, empuja una pierna hacia atras y arriba manteniendo la rodilla flexionada.", tip: "Evita arquear la espalda baja; el movimiento viene de la cadera." },
      { name: "Sentadilla bulgara", equipment: "Mancuernas y banco", primary: "Gluteo mayor", description: "Con el pie trasero elevado en un banco, baja flexionando la rodilla delantera hasta 90 grados.", tip: "Inclinar un poco mas el torso al frente enfatiza mas el gluteo." },
      { name: "Puente de gluteos a una pierna", equipment: "Peso corporal", primary: "Gluteo mayor", description: "Acostado boca arriba, eleva la cadera apoyando solo un pie en el piso mientras la otra pierna esta extendida.", tip: "Muy util para corregir desequilibrios entre ambos gluteos." },
    ],
  },
  {
    slug: "pantorrillas",
    name: "Pantorrillas",
    accent: "#5ee7d8",
    exercises: [
      { name: "Elevacion de talones de pie", equipment: "Maquina o mancuernas", primary: "Gastrocnemio", description: "De pie, eleva los talones lo mas alto posible y baja controladamente hasta sentir el estiramiento.", tip: "Haz una pausa de 1-2 segundos arriba para mayor activacion." },
      { name: "Elevacion de talones sentado", equipment: "Maquina sentada", primary: "Soleo", description: "Sentado con el peso sobre las rodillas, eleva los talones y baja controladamente.", tip: "Al estar flexionada la rodilla se enfatiza mas el soleo que el gastrocnemio." },
      { name: "Saltos de cuerda", equipment: "Cuerda para saltar", primary: "Pantorrillas (resistencia)", description: "Salta de forma continua impulsandote principalmente con los tobillos, no con las rodillas.", tip: "Empieza con series cortas si no tienes costumbre, es mas exigente de lo que parece." },
      { name: "Elevacion de talones en prensa", equipment: "Maquina de prensa", primary: "Gastrocnemio", description: "En la maquina de prensa, empuja solo con la punta de los pies extendiendo el tobillo.", tip: "Usa un rango de movimiento completo, bajando hasta sentir el estiramiento." },
      { name: "Elevacion de talones a una pierna", equipment: "Peso corporal o mancuerna", primary: "Gastrocnemio", description: "De pie sobre una pierna, eleva el talon lo mas alto posible y baja controladamente.", tip: "Sujetate de algo para mantener el equilibrio si lo necesitas." },
      { name: "Saltos en caja (box jumps)", equipment: "Cajon pliometrico", primary: "Pantorrillas y cuadriceps", description: "Salta con ambos pies sobre un cajon, aterrizando suave con las rodillas flexionadas.", tip: "Baja del cajon caminando, no saltando, para cuidar las articulaciones." },
      { name: "Caminata en punta de pies", equipment: "Peso corporal", primary: "Gastrocnemio y soleo", description: "Camina una distancia corta manteniendo los talones elevados todo el tiempo.", tip: "Es un buen ejercicio de activacion antes de entrenar piernas." },
      { name: "Elevacion de talones en escalon", equipment: "Escalon o step", primary: "Gastrocnemio", description: "Con la punta de los pies en el borde de un escalon, baja el talon por debajo del nivel del escalon y sube.", tip: "El rango de movimiento extra por debajo del escalon aumenta el estiramiento." },
      { name: "Burpees con salto", equipment: "Peso corporal", primary: "Pantorrillas y cuerpo completo", description: "Combina una flexion, una sentadilla y un salto vertical de forma continua.", tip: "Excelente para trabajar resistencia de pantorrillas junto con cardio." },
      { name: "Saltos con banda elastica", equipment: "Banda de resistencia", primary: "Pantorrillas (resistencia)", description: "Con la banda alrededor de los tobillos, realiza pequenos saltos laterales o verticales.", tip: "Controla el aterrizaje para proteger tobillos y rodillas." },
    ],
  },
  {
    slug: "abdominales",
    name: "Abdominales",
    accent: "#ffd166",
    exercises: [
      { name: "Plancha (plank)", equipment: "Peso corporal", primary: "Recto abdominal y core", description: "Apoya antebrazos y puntas de los pies, manteniendo el cuerpo en linea recta de cabeza a talones.", tip: "Aprieta gluteos y abdomen para evitar que la cadera se hunda." },
      { name: "Crunch abdominal", equipment: "Peso corporal", primary: "Recto abdominal", description: "Acostado con las rodillas flexionadas, eleva los hombros del piso contrayendo el abdomen.", tip: "No tires del cuello con las manos; el movimiento lo hace el abdomen." },
      { name: "Elevacion de piernas", equipment: "Peso corporal o barra de dominadas", primary: "Recto abdominal inferior", description: "Acostado o colgado, eleva las piernas hacia el pecho manteniendo el control en la bajada.", tip: "Evita usar impulso; baja las piernas lentamente." },
      { name: "Plancha lateral (side plank)", equipment: "Peso corporal", primary: "Oblicuos", description: "Apoyado en un antebrazo de lado, manten el cuerpo en linea recta sin dejar caer la cadera.", tip: "Manten el hombro alineado directamente sobre el codo de apoyo." },
      { name: "Giros rusos (Russian twist)", equipment: "Disco o mancuerna (opcional)", primary: "Oblicuos", description: "Sentado con el torso ligeramente reclinado, gira el peso de un lado a otro del cuerpo.", tip: "Manten los pies elevados solo si tu core ya tiene buena base de fuerza." },
      { name: "Rueda abdominal (ab wheel rollout)", equipment: "Rueda abdominal", primary: "Recto abdominal y core", description: "De rodillas, rueda hacia adelante manteniendo el core apretado y regresa a la posicion inicial.", tip: "No dejes que la espalda baja se arquee; detente si pierdes el control." },
      { name: "Mountain climbers", equipment: "Peso corporal", primary: "Core (con componente cardio)", description: "En posicion de plancha alta, lleva las rodillas al pecho alternando rapidamente.", tip: "Manten la cadera baja y estable, sin que suba y baje en exceso." },
      { name: "Crunch en polea (cable crunch)", equipment: "Polea alta con cuerda", primary: "Recto abdominal", description: "Arrodillado frente a la polea, flexiona el torso hacia abajo contrayendo el abdomen.", tip: "El movimiento nace de la cintura, no de tirar con los brazos." },
      { name: "Plancha con toque de hombro", equipment: "Peso corporal", primary: "Core (anti-rotacion)", description: "En plancha alta, toca el hombro contrario con una mano alternando, manteniendo la cadera estable.", tip: "Separa un poco mas los pies si te cuesta mantener el equilibrio." },
      { name: "Elevacion de rodillas colgado", equipment: "Barra de dominadas", primary: "Recto abdominal inferior", description: "Colgado de la barra, eleva las rodillas hacia el pecho contrayendo el abdomen.", tip: "Evita balancear el cuerpo; usa solo la fuerza del abdomen." },
    ],
  },
  {
    slug: "cintura",
    name: "Cintura",
    accent: "#c792ea",
    exercises: [
      { name: "Plancha lateral", equipment: "Peso corporal", primary: "Oblicuos", description: "Apoyado en un antebrazo de lado, manten el cuerpo en linea recta sin dejar caer la cadera.", tip: "Aumenta el tiempo poco a poco para ganar resistencia en el core lateral." },
      { name: "Giros rusos", equipment: "Disco o mancuerna", primary: "Oblicuos", description: "Sentado con el torso reclinado, gira el peso de un lado a otro del cuerpo de forma controlada.", tip: "Gira desde la cintura, no solo moviendo los brazos." },
      { name: "Woodchop en polea", equipment: "Polea alta o baja", primary: "Oblicuos (rotacion de core)", description: "Tira del cable en diagonal, de un hombro hacia la cadera opuesta, girando el torso.", tip: "Manten las caderas relativamente fijas y deja que gire el torso." },
      { name: "Elevacion de cadera lateral (side plank hip lift)", equipment: "Peso corporal", primary: "Oblicuos", description: "En plancha lateral, baja y sube la cadera sin tocar el piso.", tip: "Movimiento corto y controlado, no busques bajar demasiado rapido." },
      { name: "Flexion lateral de tronco con mancuerna", equipment: "Mancuerna", primary: "Oblicuos", description: "De pie con una mancuerna a un lado, flexiona el torso lateralmente y regresa al centro.", tip: "Usa peso ligero; el objetivo es tonificar, no sobrecargar la zona lumbar." },
      { name: "Plancha con rotacion (plank with rotation)", equipment: "Peso corporal", primary: "Oblicuos y core", description: "Desde plancha lateral, gira el torso llevando el brazo libre por debajo del cuerpo y de vuelta arriba.", tip: "Controla la rotacion, no dejes que la cadera se caiga durante el giro." },
      { name: "Russian twist con piernas elevadas", equipment: "Disco o mancuerna", primary: "Oblicuos (avanzado)", description: "Igual que el giro ruso, pero manteniendo los pies elevados del piso todo el tiempo.", tip: "Solo progresa a esta variante cuando domines la version con pies apoyados." },
      { name: "Bicycle crunch", equipment: "Peso corporal", primary: "Recto abdominal y oblicuos", description: "Acostado, lleva el codo hacia la rodilla contraria alternando en un movimiento de pedaleo.", tip: "Hazlo despacio y controlado; la velocidad reduce la activacion muscular." },
      { name: "Woodchop con banda elastica", equipment: "Banda de resistencia", primary: "Oblicuos", description: "Con la banda anclada baja, tira en diagonal hacia el hombro opuesto girando el torso.", tip: "Buena alternativa a la polea cuando entrenas en casa." },
      { name: "Plancha con paso lateral (plank walkout)", equipment: "Peso corporal", primary: "Core completo", description: "En plancha alta, desplaza manos y pies hacia un lado y luego hacia el otro manteniendo la cadera estable.", tip: "Manten el core apretado en todo momento para no perder la alineacion." },
    ],
  },
  {
    slug: "espalda-baja",
    name: "Espalda baja",
    accent: "#f4a261",
    exercises: [
      { name: "Hiperextensiones", equipment: "Banco romano", primary: "Erectores espinales", description: "Con la cadera apoyada en el banco, baja el torso controladamente y sube hasta alinear el cuerpo.", tip: "No hiperextiendas de mas al subir; solo hasta la linea recta del cuerpo." },
      { name: "Peso muerto rumano", equipment: "Barra o mancuernas", primary: "Espalda baja e isquiotibiales", description: "Con las rodillas ligeramente flexionadas, baja el peso deslizandolo cerca de las piernas manteniendo la espalda recta.", tip: "Nunca redondees la espalda baja durante el descenso." },
      { name: "Bird dog", equipment: "Peso corporal", primary: "Core y espalda baja (estabilidad)", description: "En cuadrupedia, extiende un brazo y la pierna contraria a la vez, manteniendo la cadera estable.", tip: "Muevete lento y controlado; la calidad importa mas que la velocidad." },
      { name: "Buenos dias (good mornings)", equipment: "Barra libre", primary: "Espalda baja e isquiotibiales", description: "Con la barra sobre los trapecios, inclina el torso hacia adelante desde la cadera manteniendo la espalda recta.", tip: "Empieza con peso muy ligero; requiere buena tecnica y movilidad de cadera." },
      { name: "Superman", equipment: "Peso corporal", primary: "Erectores espinales", description: "Acostado boca abajo, eleva simultaneamente brazos y piernas del piso y manten unos segundos.", tip: "Aprieta los gluteos para proteger la zona lumbar durante la elevacion." },
      { name: "Peso muerto sumo", equipment: "Barra libre", primary: "Espalda baja y gluteos", description: "Con las piernas bien abiertas y agarre estrecho, levanta la barra extendiendo cadera y rodillas a la vez.", tip: "El torso queda mas vertical que en el peso muerto convencional, cuidando mas la zona lumbar." },
      { name: "Plancha (plank)", equipment: "Peso corporal", primary: "Core y espalda baja (estabilidad)", description: "Apoya antebrazos y puntas de los pies, manteniendo el cuerpo en linea recta.", tip: "Un core fuerte protege directamente la espalda baja en otros ejercicios." },
      { name: "Extension de espalda en el piso (cobra)", equipment: "Peso corporal", primary: "Erectores espinales", description: "Acostado boca abajo, apoya las manos cerca de los hombros y eleva el pecho del piso.", tip: "Movimiento suave, ideal como ejercicio de movilidad y activacion." },
      { name: "Remo con barra (postura)", equipment: "Barra libre", primary: "Espalda baja (estabilidad) y dorsal", description: "Con el torso inclinado hacia adelante, tira de la barra hacia el abdomen manteniendo la espalda recta.", tip: "La posicion inclinada exige que la espalda baja se mantenga firme y neutra." },
      { name: "Bird dog con banda", equipment: "Banda de resistencia", primary: "Core y espalda baja", description: "Igual que el bird dog, pero con una banda alrededor de la mano y el pie opuesto para mayor resistencia.", tip: "Agrega la banda solo cuando domines bien la tecnica sin peso." },
    ],
  },
];

export const muscleGroupBySlug = Object.fromEntries(
  muscleGroups.map((group) => [group.slug, group])
);
